### ISSUE TITLE
Failed to load module list, if module names contains character - ? 

### ISSUE THREAD

**Issue by LadyMikea** [neumatho/NostalgicPlayer#119]
If module name (sits alone or in the lha archive) contains character - ?  - error occurs when trying to load saved module list:

"Failed to load the module list. Failed with error:
The input string " was not in a correct format".

 Also, thanks for Nostalgic Player.

**Comment by neumatho** [comment]
Thanks for reporting this. I will look at it soon.

**Comment by neumatho** [comment]
It has been fixed now and will be included in the next release.

**Comment by LadyMikea** [comment]
Thank you for fast fix. I must say, Nostalgic Player plays Amiga "chip" format modules like "Hippel" or "TFMX" far better than PC version of Deliplayer 2, for example music from games "Ghost Battle" or "Wings of Death" sounds just perfect! Of course DP2 is now very old and outdated, but it is only player I now that can play various Amiga exotic "chip music" format.  Your modern player for Amiga tunes is just awesome, thanks again for hard work.
