### ISSUE TITLE
Acknowledge the usage of ancient codebase

### ISSUE THREAD

**Issue by temisu** [neumatho/NostalgicPlayer#21]
The compressors in NostalgicPlayer/Source/Agents/Decrunchers/AncientDecruncher/Formats/Streams/Xpk/ are derivate of ancient in https://github.com/temisu/ancient which is fine and allowed by the license as long as the license is included.

https://github.com/temisu/ancient/blob/master/LICENSE

Please include note of that to your repo.

Thanks

**Comment by neumatho** [comment]
Sorry, I forgot that. License file has now been added and a notice been written in the readme file.
