### ISSUE TITLE
NostalgicPlayerConsole throws System.NullReferenceException

### ISSUE THREAD

**Issue by mnerec** [neumatho/NostalgicPlayer#35]
In `Polycode.NostalgicPlayer.PlayerLibrary.Mixer.MixerVisualize.QueueChannelChange()` enabledChannels is dereferenced without checking for `null`.

Changing `Enabled = i < enabledChannels.Length ? enabledChannels[i] : true` to `Enabled = (enabledChannels != null && i < enabledChannels.Length) ? enabledChannels[i] : true` fixes the issue.

It might only be for some formats. Reproduced with PT and JamCracker mods.

**Comment by neumatho** [comment]
Thanks. Will look at it later today.

**Comment by neumatho** [comment]
Bug fixed.
