### ISSUE TITLE
4.0/5.1/7.1 --> 2.0

### ISSUE THREAD

**Issue by 7zxkv** [neumatho/NostalgicPlayer#49]
hello, 

I've noticed that there's an initialization problem if the speakers are configured in 4.0/5.1/7.1, they need to be configured in 2.0 otherwise no sound is transmitted. Would it be possible to correct this or set it via the software rather than via Windows?

best regards

**Comment by Raph99-Thanys** [comment]
Hi, i have exactly the same bug, my sound system is in 5.1 by default, if i try to launch "NostalicPlayer" with 5.1 activated, then the outpout fail to initialize (error: 0x80131500 no endpoint device could be found)

Thank for NostlgicPlayer is already really cool ;)

**Comment by neumatho** [comment]
@7zxkv, does NostalgicPlayer start playing the module, but you don't hear anything or do you get an error message like @Raph99-Thanys?

I have tried to connect a set of extra speakers as rear speaker and Windows detect them and I have set them up to 4.0. Then starting NostalgicPlayer, it plays the module just fine in the front speakers. What do I need to do to reproduce the error?

I have a pretty good idea of why you will get an error message, but it would be nice if I could test if a fix works instead of trying to do something blindfolded.

**Comment by Raph99-Thanys** [comment]
I'm here if you need help, to try/test/crashtest ;) and sorry for my strange english, i'm french ^^

**Comment by Raph99-Thanys** [comment]
![01](https://github.com/neumatho/NostalgicPlayer/assets/87669154/2a087a84-c739-4448-8526-0e6447ab5b5b)

If i try to juste launch NostalgicPlayer in 5.1, i got this error:

![02](https://github.com/neumatho/NostalgicPlayer/assets/87669154/c28062b9-c194-4501-a0d8-42d1facb35bc)

But if i put my system in "Stéréo" (2.0) then NostalgicPlayer work like a charm ^^'
![03](https://github.com/neumatho/NostalgicPlayer/assets/87669154/38be90ac-68c9-4d52-bb17-5e9f06c5d534)

by the way if you need it, i have more than 5k of **compressed** Amiga Music Files, in a lot of different rip, some are old AND in real Amiga "Original Direct Rip", i can put them on 1fichier.com for you, juste ask ;)

**Comment by neumatho** [comment]
I also have Realtek and this is exactly what I'm doing, but it still works. I know where in the code the error message is shown and what it's doing (I trying to get an output from Windows which can take either stereo or mono), and this is failing on your machine. Which version of Windows do you use? Windows 10 or 11?

Well, I have an idea to get it to work.

Thanks to offer me your music, but I have a lot already (downloaded whole Aminet and Modland). You can check out my homepage, there you can download all the modules I have in the supported formats. As more formats are supported, more modules will be available.

**Comment by Raph99-Thanys** [comment]
Hello, i'm using Windows 10 (10.7 version 21H2)

**Comment by neumatho** [comment]
I have now tried on a Windows 10 and there it also work fine. Strange.

Well, if you want, you can be my tester to see if my solution work or not when done.

**Comment by Raph99-Thanys** [comment]
I'm ready for it! 
![rmb](https://github.com/neumatho/NostalgicPlayer/assets/87669154/59920c00-ea4e-48d3-91d2-b30e12f2b831)

**Comment by neumatho** [comment]
I have just commited a fix (hopefully). Can you compile by yourself or do you need a compiled package to test with?

**Comment by Raph99-Thanys** [comment]
i need a compiled package plz :)

**Comment by neumatho** [comment]
Here you go:
[NostalgicPlayer_Test.zip](https://github.com/neumatho/NostalgicPlayer/files/13629159/NostalgicPlayer_Test.zip)

**Comment by Raph99-Thanys** [comment]
AANNNNNDD!!!???? it's a win! 
![mailspring_VUkFZUxAdH](https://github.com/neumatho/NostalgicPlayer/assets/87669154/6d63b2a4-013c-4f33-979e-2c2dfc067726)

Good job!! :)

**Comment by neumatho** [comment]
Great! I will close the issue then.

**Comment by 7zxkv** [comment]
thanks Neumatho and raph99 ;)

**Comment by neumatho** [comment]
Hi @Raph99-Thanys,

I'm just wondering how your audio setup is. Do you use a receiver which can take 5.1 Jacks and if yes, what the name of that receiver. I was thinking of adding real surround support if I can find a receiver. My currently receiver only have stereo input, but support the old Prologic surround format.

-Thomas

**Comment by Raph99-Thanys** [comment]
Hi, i'm using a 5.1 System from Creative, an OLLLDDD! one...
This one: "Creative Labs T6300 5.1" (https://www.1fodiscount.com/p122968-enceintes-creative-labs-t6300-51/)
Directly plugged on my "realteack" sound system from my mother board, with 2.5 jacks (MB = MSI MAG B660 Mortar)
it's a Physical 5.1 System

**Comment by neumatho** [comment]
Thanks. Talk continued on discussion #54.
