### ISSUE TITLE
How To Use Disk Saver?

### ISSUE THREAD

**Issue by ariesps** [neumatho/NostalgicPlayer#55]
My idea is to "convert" from modules to FLAC or WAV Files.
I select settings on Agent Windows, but no output file is created.

Any help would be appreciated.

**Comment by neumatho** [comment]
You also need to open the settings window, go to the mixer tab and select Disk Saver as the output agent. Remember to press "Apply" or "Ok".

**Comment by ariesps** [comment]
Yesss! Now it seems to work. Thanks for your help!

**Comment by neumatho** [comment]
You're welcome. I will close the ticket then.
