### ISSUE TITLE
NostalgicPlayer 2.3.0 crash

### ISSUE THREAD

**Issue by BackSpace54** [neumatho/NostalgicPlayer#78]
Hi,
I try to run NostalgicPlayer 2.3.0 but an error appears and NP exits:

![image](https://github.com/neumatho/NostalgicPlayer/assets/57332400/f34cffa3-d886-4f30-918b-e536ef54a176)

Do you need more infos?
On the same machine NostalgicPlayer 2.2.0 works flawless.

**Comment by neumatho** [comment]
Have you installed it from Microsoft Store or do you run the version from the release page?

**Comment by BackSpace54** [comment]
Extracted NP 2.3 in a clean directory, that solved the problem.
Issue fixed, thanks.
